version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - automation
    reviewers:
      - ghul0

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    groups:
      ci-actions:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - ci
    reviewers:
      - ghul0

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker
    reviewers:
      - ghul0
